<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\MenuItem;
use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Create the 7 Canonical Categories
        $categories = [
            'le-pizze-classiche' => Category::updateOrCreate(
                ['slug' => 'le-pizze-classiche'],
                [
                    'name_de'        => 'Le Pizze Classiche',
                    'name_en'        => 'Classic Neapolitan Pizzas',
                    'description_de' => 'Traditionelle neapolitanische Pizze mit San Marzano D.O.P. Tomatensauce und Sorrento Fior di Latte.',
                    'description_en' => 'Traditional Neapolitan pizzas with San Marzano D.O.P. tomato sauce and Sorrento Fior di Latte.',
                    'sort_order'     => 1,
                    'is_active'      => true,
                ]
            ),
            'pizze-gialle' => Category::updateOrCreate(
                ['slug' => 'pizze-gialle'],
                [
                    'name_de'        => 'Pizze Gialle',
                    'name_en'        => 'Yellow Datterino Pizzas',
                    'description_de' => 'Spezialitäten mit sonnengereifter gelber Datteltomatensauce aus Kampanien.',
                    'description_en' => 'Specialties prepared with sweet yellow Datterino tomato sauce from Campania.',
                    'sort_order'     => 2,
                    'is_active'      => true,
                ]
            ),
            'pizze-bianche-calzone' => Category::updateOrCreate(
                ['slug' => 'pizze-bianche-calzone'],
                [
                    'name_de'        => 'Pizze Bianche & Calzone',
                    'name_en'        => 'White Pizzas & Calzones',
                    'description_de' => 'Köstlichkeiten ohne Tomatensauce sowie gefüllte und frittierte neapolitanische Calzoni.',
                    'description_en' => 'Delicacies without tomato sauce as well as folded Neapolitan calzones.',
                    'sort_order'     => 3,
                    'is_active'      => true,
                ]
            ),
            'antipasti-insalata' => Category::updateOrCreate(
                ['slug' => 'antipasti-insalata'],
                [
                    'name_de'        => 'Antipasti & Insalata',
                    'name_en'        => 'Starters & Salads',
                    'description_de' => 'Ofenfrische Focacce, cremige Burrata und knackige mediterrane Salate.',
                    'description_en' => 'Fresh oven-baked focaccias, creamy burrata and crisp Mediterranean salads.',
                    'sort_order'     => 4,
                    'is_active'      => true,
                ]
            ),
            'pasta-fatta-in-casa' => Category::updateOrCreate(
                ['slug' => 'pasta-fatta-in-casa'],
                [
                    'name_de'        => 'Pasta Fatta in Casa',
                    'name_en'        => 'Homemade Fresh Pasta',
                    'description_de' => 'Täglich frisch handgemachte Pasta nach authentischen italienischen Familienrezepten.',
                    'description_en' => 'Daily fresh artisanal pasta prepared according to authentic Italian family recipes.',
                    'sort_order'     => 5,
                    'is_active'      => true,
                ]
            ),
            'dolci' => Category::updateOrCreate(
                ['slug' => 'dolci'],
                [
                    'name_de'        => 'Dolci Artigianali',
                    'name_en'        => 'Artisanal Desserts',
                    'description_de' => 'Hausgemachtes Tiramisù, gefüllte Profiteroles und süße Pizze für 2 Personen.',
                    'description_en' => 'Homemade tiramisu, filled profiteroles and sweet pizzas for two.',
                    'sort_order'     => 6,
                    'is_active'      => true,
                ]
            ),
            'getraenke-bier' => Category::updateOrCreate(
                ['slug' => 'getraenke-bier'],
                [
                    'name_de'        => 'Getränke & Italienisches Bier',
                    'name_en'        => 'Beverages & Italian Beers',
                    'description_de' => 'Erfrischende italienische Mineralwässer, Limonaden und Spezial-Biere (Ichnusa, Moretti, Messina).',
                    'description_en' => 'Refreshing Italian mineral waters, sodas, and specialty beers (Ichnusa, Moretti, Messina).',
                    'sort_order'     => 7,
                    'is_active'      => true,
                ]
            ),
        ];

        // 2. The 51 Canonical Menu Items Registry
        $items = [
            // Category 1: Le Pizze Classiche (Items 1 - 13)
            [
                'category_id'    => $categories['le-pizze-classiche']->id,
                'slug'           => 'marinara',
                'name'           => 'Marinara',
                'ingredients_de' => 'San Marzano Tomatensauce, Oregano, Knoblauch, Basilikum',
                'ingredients_en' => 'San Marzano tomato sauce, oregano, garlic, fresh basil',
                'base_price'     => 8.50,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'pizza_marinara',
                'allergens'      => ['A'],
            ],
            [
                'category_id'    => $categories['le-pizze-classiche']->id,
                'slug'           => 'regina-margherita',
                'name'           => 'Regina Margherita',
                'ingredients_de' => 'San Marzano Tomatensauce, Fior di Latte aus Sorrento, Basilikum',
                'ingredients_en' => 'San Marzano tomato sauce, Sorrento Fior di Latte, fresh basil',
                'base_price'     => 9.90,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'pizza_margherita',
                'allergens'      => ['A', 'G'],
            ],
            [
                'category_id'    => $categories['le-pizze-classiche']->id,
                'slug'           => 'cotto',
                'name'           => 'Cotto',
                'ingredients_de' => 'San Marzano Tomatensauce, Fior di Latte aus Sorrento, Prosciutto Cotto, Basilikum',
                'ingredients_en' => 'San Marzano tomato sauce, Sorrento Fior di Latte, cooked Italian ham, fresh basil',
                'base_price'     => 13.90,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'pizza_cotto',
                'allergens'      => ['A', 'G'],
            ],
            [
                'category_id'    => $categories['le-pizze-classiche']->id,
                'slug'           => 'salame',
                'name'           => 'Salame',
                'ingredients_de' => 'San Marzano Tomatensauce, Fior di Latte aus Sorrento, Salami aus Neapel, Basilikum',
                'ingredients_en' => 'San Marzano tomato sauce, Sorrento Fior di Latte, Neapolitan salami, fresh basil',
                'base_price'     => 13.90,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'pizza_salame',
                'allergens'      => ['A', 'G'],
            ],
            [
                'category_id'    => $categories['le-pizze-classiche']->id,
                'slug'           => 'diabola-2-0',
                'name'           => 'Diabola 2.0',
                'ingredients_de' => 'San Marzano Tomatensauce, Fior di Latte aus Sorrento, Scharfe Salami, Jalapeño-Creme, Basilikum',
                'ingredients_en' => 'San Marzano tomato sauce, Sorrento Fior di Latte, spicy salami, jalapeño cream, fresh basil',
                'base_price'     => 14.30,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'pizza_diabola',
                'allergens'      => ['A', 'G'],
            ],
            [
                'category_id'    => $categories['le-pizze-classiche']->id,
                'slug'           => 'bufala',
                'name'           => 'Bufala',
                'ingredients_de' => 'San Marzano Tomatensauce, Büffelmozzarella aus Neapel D.O.P., Basilikum',
                'ingredients_en' => 'San Marzano tomato sauce, Buffalo Mozzarella from Naples D.O.P., fresh basil',
                'base_price'     => 13.90,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'pizza_bufala',
                'allergens'      => ['A', 'G'],
            ],
            [
                'category_id'    => $categories['le-pizze-classiche']->id,
                'slug'           => 'vegetariana',
                'name'           => 'Vegetariana',
                'ingredients_de' => 'San Marzano Tomatensauce, Fior di Latte aus Sorrento, Frisches Grillgemüse, Basilikum',
                'ingredients_en' => 'San Marzano tomato sauce, Sorrento Fior di Latte, grilled fresh vegetables, fresh basil',
                'base_price'     => 14.60,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'pizza_vegetariana',
                'allergens'      => ['A', 'G'],
            ],
            [
                'category_id'    => $categories['le-pizze-classiche']->id,
                'slug'           => 'testa-rossa',
                'name'           => 'Testa Rossa',
                'ingredients_de' => 'San Marzano Tomatensauce, Marinierte Sardellenfilets, Kapern, Oliven, Halbgetrocknete Tomaten, Basilikum',
                'ingredients_en' => 'San Marzano tomato sauce, marinated anchovy fillets, capers, olives, semi-dried tomatoes, basil',
                'base_price'     => 14.70,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'pizza_testa_rossa',
                'allergens'      => ['A', 'D', 'O'],
            ],
            [
                'category_id'    => $categories['le-pizze-classiche']->id,
                'slug'           => '4-stagioni',
                'name'           => '4 Stagioni',
                'ingredients_de' => 'San Marzano Tomatensauce, Fior di Latte aus Sorrento, Prosciutto Cotto, Salami aus Neapel, Artischocken, Oliven, Champignons, Basilikum',
                'ingredients_en' => 'San Marzano tomato sauce, Sorrento Fior di Latte, cooked ham, Neapolitan salami, artichokes, olives, mushrooms, basil',
                'base_price'     => 14.90,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'pizza_4stagioni',
                'allergens'      => ['A', 'G'],
            ],
            [
                'category_id'    => $categories['le-pizze-classiche']->id,
                'slug'           => 'red-passion',
                'name'           => 'Red Passion',
                'ingredients_de' => 'San Marzano Tomatensauce, Fior di Latte aus Sorrento, Rucola, Prosciutto Crudo San Daniele 24 Monate D.O.P., Marinierte Kirschtomaten (Gelb & Rot), Grana Padano 24 Monate D.O.P., Basilikum',
                'ingredients_en' => 'San Marzano tomato sauce, Sorrento Fior di Latte, arugula, 24-month San Daniele ham D.O.P., marinated yellow & red cherry tomatoes, Grana Padano D.O.P., basil',
                'base_price'     => 15.50,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'pizza_red_passion',
                'allergens'      => ['A', 'G'],
            ],
            [
                'category_id'    => $categories['le-pizze-classiche']->id,
                'slug'           => 'tropea',
                'name'           => 'Tropea',
                'ingredients_de' => 'San Marzano Tomatensauce, Fior di Latte aus Sorrento, Karamellisierte rote Zwiebel, Oliven, Thunfisch, Basilikum',
                'ingredients_en' => 'San Marzano tomato sauce, Sorrento Fior di Latte, caramelized red Tropea onion, olives, tuna, basil',
                'base_price'     => 13.50,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'pizza_tropea',
                'allergens'      => ['A', 'D', 'G'],
            ],
            [
                'category_id'    => $categories['le-pizze-classiche']->id,
                'slug'           => 'secret-love',
                'name'           => 'Secret Love',
                'ingredients_de' => 'San Marzano Tomatensauce, Fior di Latte aus Sorrento, Getrocknete Tomaten, Marinierte Kirschtomaten (Gelb & Rot), Ligurisches Pesto',
                'ingredients_en' => 'San Marzano tomato sauce, Sorrento Fior di Latte, dried tomatoes, marinated yellow & red cherry tomatoes, Ligurian pesto',
                'base_price'     => 14.60,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'pizza_secret_love',
                'allergens'      => ['A', 'G'],
            ],
            [
                'category_id'    => $categories['le-pizze-classiche']->id,
                'slug'           => 'bresaola-valtellinese',
                'name'           => 'Bresaola Valtellinese',
                'ingredients_de' => 'San Marzano Tomatensauce, Fior di Latte aus Sorrento, Rucola, Marinierte Kirschtomaten (Gelb & Rot), Bresaola Valtellinese',
                'ingredients_en' => 'San Marzano tomato sauce, Sorrento Fior di Latte, arugula, marinated cherry tomatoes, Bresaola della Valtellina',
                'base_price'     => 16.90,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'pizza_bresaola',
                'allergens'      => ['A', 'G'],
            ],

            // Category 2: Pizze Gialle (Items 14 - 19)
            [
                'category_id'    => $categories['pizze-gialle']->id,
                'slug'           => 'yellow-marinara',
                'name'           => 'Yellow Marinara',
                'ingredients_de' => 'Gelbe Datteltomatensauce, Oregano, Knoblauch, Basilikum',
                'ingredients_en' => 'Yellow Datterino tomato sauce, oregano, garlic, fresh basil',
                'base_price'     => 8.50,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'pizza_yellow_marinara',
                'allergens'      => ['A'],
            ],
            [
                'category_id'    => $categories['pizze-gialle']->id,
                'slug'           => 'yellow-bufala',
                'name'           => 'Yellow Bufala',
                'ingredients_de' => 'Gelbe Datteltomatensauce, Büffelmozzarella D.O.P., Marinierte Kirschtomaten (Gelb & Rot), Basilikum Pesto',
                'ingredients_en' => 'Yellow Datterino tomato sauce, Buffalo Mozzarella D.O.P., marinated cherry tomatoes, basil pesto',
                'base_price'     => 14.90,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'pizza_yellow_bufala',
                'allergens'      => ['A', 'G'],
            ],
            [
                'category_id'    => $categories['pizze-gialle']->id,
                'slug'           => 'mediterranea',
                'name'           => 'Mediterranea',
                'ingredients_de' => 'Gelbe Datteltomatensauce, Fior di Latte aus Sorrento, Karamellisierte rote Zwiebel, Halbgetrocknete Tomaten, Thunfisch, Oregano, Basilikum',
                'ingredients_en' => 'Yellow Datterino tomato sauce, Sorrento Fior di Latte, caramelized red onion, semi-dried tomatoes, tuna, oregano, basil',
                'base_price'     => 14.80,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'pizza_mediterranea',
                'allergens'      => ['A', 'D', 'G'],
            ],
            [
                'category_id'    => $categories['pizze-gialle']->id,
                'slug'           => 'testa-gialla',
                'name'           => 'Testa Gialla',
                'ingredients_de' => 'Gelbe Datteltomatensauce, Knoblauch, Kapern, Oliven, Sardellen, Marinierte Kirschtomaten (Gelb & Rot), Basilikum',
                'ingredients_en' => 'Yellow Datterino tomato sauce, garlic, capers, olives, anchovies, marinated cherry tomatoes, basil',
                'base_price'     => 14.70,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'pizza_testa_gialla',
                'allergens'      => ['A', 'D'],
            ],
            [
                'category_id'    => $categories['pizze-gialle']->id,
                'slug'           => 'super-parmigiana',
                'name'           => 'Super Parmigiana',
                'ingredients_de' => 'Gelbe Datteltomatensauce, Fior di Latte aus Sorrento, Gegrillte Melanzani, Grana Padano 24 Monate D.O.P., Basilikum',
                'ingredients_en' => 'Yellow Datterino sauce, Sorrento Fior di Latte, grilled eggplant, 24-month Grana Padano D.O.P., basil',
                'base_price'     => 14.60,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'pizza_super_parmigiana',
                'allergens'      => ['A', 'G'],
            ],
            [
                'category_id'    => $categories['pizze-gialle']->id,
                'slug'           => 'yellow-margherita',
                'name'           => 'Yellow Margherita',
                'ingredients_de' => 'Gelbe Datteltomatensauce, Fior di Latte aus Sorrento, Basilikum',
                'ingredients_en' => 'Yellow Datterino tomato sauce, Sorrento Fior di Latte, fresh basil',
                'base_price'     => 10.50,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'pizza_yellow_margherita',
                'allergens'      => ['A', 'G'],
            ],

            // Category 3: Pizze Bianche & Calzone (Items 20 - 23)
            [
                'category_id'    => $categories['pizze-bianche-calzone']->id,
                'slug'           => '4-formaggi',
                'name'           => '4 Formaggi',
                'ingredients_de' => 'Fior di Latte aus Sorrento, Grana Padano 24 Monate D.O.P., Gorgonzola Dolce D.O.P., Ricotta, Roter Pfeffer, Basilikum',
                'ingredients_en' => 'Sorrento Fior di Latte, Grana Padano D.O.P., Gorgonzola Dolce D.O.P., Ricotta, pink pepper, basil',
                'base_price'     => 14.60,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'pizza_4formaggi',
                'allergens'      => ['A', 'G'],
            ],
            [
                'category_id'    => $categories['pizze-bianche-calzone']->id,
                'slug'           => 'sophia-loren',
                'name'           => 'Sophia Loren',
                'ingredients_de' => 'Fior di Latte aus Sorrento, Pistazienmortadella, Pistazien, Pistaziencreme, Basilikum',
                'ingredients_en' => 'Sorrento Fior di Latte, pistachio mortadella, crushed pistachios, pistachio cream, fresh basil',
                'base_price'     => 16.60,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'pizza_sophia_loren',
                'allergens'      => ['A', 'G', 'H'],
            ],
            [
                'category_id'    => $categories['pizze-bianche-calzone']->id,
                'slug'           => 'calzone-vaticano',
                'name'           => 'Calzone Vaticano',
                'ingredients_de' => 'San Marzano Tomatensauce, Fior di Latte aus Sorrento, Prosciutto Cotto, Salami, Champignons, Basilikum',
                'ingredients_en' => 'San Marzano tomato sauce, Sorrento Fior di Latte, cooked ham, salami, mushrooms, basil',
                'base_price'     => 14.90,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'calzone_vaticano',
                'allergens'      => ['A', 'G'],
            ],
            [
                'category_id'    => $categories['pizze-bianche-calzone']->id,
                'slug'           => 'calzone-emotion',
                'name'           => 'Calzone Emotion',
                'ingredients_de' => 'Gelbe Datteltomatensauce, Fior di Latte aus Sorrento, Pistazienmortadella',
                'ingredients_en' => 'Yellow Datterino tomato sauce, Sorrento Fior di Latte, pistachio mortadella',
                'base_price'     => 15.80,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'model_3d_key'   => 'calzone_emotion',
                'allergens'      => ['A', 'G', 'H'],
            ],

            // Category 4: Antipasti & Insalata (Items 24 - 30)
            [
                'category_id'    => $categories['antipasti-insalata']->id,
                'slug'           => 'focaccia-knoblauch',
                'name'           => 'Focaccia Knoblauch',
                'ingredients_de' => 'Frische neapolitanische Focaccia mit Knoblauchöl und Rosmarin',
                'ingredients_en' => 'Fresh Neapolitan focaccia with garlic oil and rosemary',
                'base_price'     => 5.50,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'allergens'      => ['A'],
            ],
            [
                'category_id'    => $categories['antipasti-insalata']->id,
                'slug'           => 'focaccia-pesto',
                'name'           => 'Focaccia Pesto',
                'ingredients_de' => 'Frische neapolitanische Focaccia mit ligurischem Basilikumpesto',
                'ingredients_en' => 'Fresh Neapolitan focaccia with Ligurian basil pesto',
                'base_price'     => 5.50,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'allergens'      => ['A'],
            ],
            [
                'category_id'    => $categories['antipasti-insalata']->id,
                'slug'           => 'focaccia-chili',
                'name'           => 'Focaccia Chili',
                'ingredients_de' => 'Frische neapolitanische Focaccia mit kalabrischem Chiliöl',
                'ingredients_en' => 'Fresh Neapolitan focaccia with Calabrian chili oil',
                'base_price'     => 5.50,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'allergens'      => ['A'],
            ],
            [
                'category_id'    => $categories['antipasti-insalata']->id,
                'slug'           => 'caprese-di-bufala',
                'name'           => 'Caprese di Bufala',
                'ingredients_de' => 'Rucola, Marinierte Kirschtomaten (rot-gelb), Büffelmozzarella',
                'ingredients_en' => 'Arugula, marinated red & yellow cherry tomatoes, Buffalo Mozzarella D.O.P.',
                'base_price'     => 13.50,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'allergens'      => ['G'],
            ],
            [
                'category_id'    => $categories['antipasti-insalata']->id,
                'slug'           => 'insalata-rucola',
                'name'           => 'Insalata Rucola',
                'ingredients_de' => 'Rucola, Marinierte Kirschtomaten, Grana Padano 24 Monate D.O.P.',
                'ingredients_en' => 'Arugula, marinated cherry tomatoes, 24-month Grana Padano D.O.P.',
                'base_price'     => 8.90,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'allergens'      => ['G'],
            ],
            [
                'category_id'    => $categories['antipasti-insalata']->id,
                'slug'           => 'insalata-pinna-gialla',
                'name'           => 'Insalata Pinna Gialla',
                'ingredients_de' => 'Thunfisch, Zwiebel, Marinierte Kirschtomaten, Oliven, Olivenöl',
                'ingredients_en' => 'Yellowfin tuna, red onion, marinated cherry tomatoes, olives, extra virgin olive oil',
                'base_price'     => 10.90,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'allergens'      => ['D'],
            ],
            [
                'category_id'    => $categories['antipasti-insalata']->id,
                'slug'           => 'insalata-verde',
                'name'           => 'Insalata Verde (Beilagensalat)',
                'ingredients_de' => 'Knackiger Blattsalat mit feinem Olivenöl-Dressing',
                'ingredients_en' => 'Crisp mixed green salad with extra virgin olive oil dressing',
                'base_price'     => 4.80,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'allergens'      => [],
            ],

            // Category 5: Pasta Fatta in Casa (Items 31 - 39)
            [
                'category_id'    => $categories['pasta-fatta-in-casa']->id,
                'slug'           => 'spaghetti-pomodoro',
                'name'           => 'Spaghetti Pomodoro (350g)',
                'ingredients_de' => 'Tomatensauce, Grana Padano, Basilikum',
                'ingredients_en' => 'Slow-simmered tomato sauce, Grana Padano, fresh basil',
                'base_price'     => 9.90,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'serving_size'   => '350g',
                'allergens'      => ['A', 'L'],
            ],
            [
                'category_id'    => $categories['pasta-fatta-in-casa']->id,
                'slug'           => 'tagliatelle-ragou-bolognese',
                'name'           => 'Tagliatelle Ragou Bolognese (300g)',
                'ingredients_de' => 'Ragou Bolognese (gemischt), Grana Padano, Basilikum',
                'ingredients_en' => 'Traditional mixed meat Bolognese ragù, Grana Padano, fresh basil',
                'base_price'     => 12.50,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'serving_size'   => '300g',
                'allergens'      => ['A', 'C', 'G', 'L'],
            ],
            [
                'category_id'    => $categories['pasta-fatta-in-casa']->id,
                'slug'           => 'garganelli-al-salmone',
                'name'           => 'Garganelli Al Salmone (300g)',
                'ingredients_de' => 'Räucherlachs, Getrocknete Tomaten, Basilikum',
                'ingredients_en' => 'Smoked salmon, sun-dried tomatoes, light creamy sauce, basil',
                'base_price'     => 12.90,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'serving_size'   => '300g',
                'allergens'      => ['A', 'C', 'D', 'G'],
            ],
            [
                'category_id'    => $categories['pasta-fatta-in-casa']->id,
                'slug'           => 'raviolo-pomodoro-datterino',
                'name'           => 'Raviolo Pomodoro Datterino (350g)',
                'ingredients_de' => 'Mit Ricotta gefüllte Ravioli, Datteltomatensauce, Basilikum, Grana Padano',
                'ingredients_en' => 'Ricotta-stuffed ravioli, sweet Datterino tomato sauce, basil, Grana Padano',
                'base_price'     => 12.50,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'serving_size'   => '350g',
                'allergens'      => ['A', 'C', 'G'],
            ],
            [
                'category_id'    => $categories['pasta-fatta-in-casa']->id,
                'slug'           => 'penne-arrabbiata',
                'name'           => 'Penne Arrabbiata (350g)',
                'ingredients_de' => 'Scharfe Tomatensauce, Grana Padano, Basilikum',
                'ingredients_en' => 'Spicy chili tomato sauce, Grana Padano, fresh basil',
                'base_price'     => 11.50,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'serving_size'   => '350g',
                'allergens'      => ['A'],
            ],
            [
                'category_id'    => $categories['pasta-fatta-in-casa']->id,
                'slug'           => 'gnocchi-pomodoro-e-mozzarella',
                'name'           => 'Gnocchi Pomodoro E Mozzarella (350g)',
                'ingredients_de' => 'Tomatensauce, Mozzarella, Grana Padano, Basilikum',
                'ingredients_en' => 'Potato gnocchi, rich tomato sauce, melted mozzarella, Grana Padano, basil',
                'base_price'     => 12.30,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'serving_size'   => '350g',
                'allergens'      => ['A', 'G'],
            ],
            [
                'category_id'    => $categories['pasta-fatta-in-casa']->id,
                'slug'           => 'strozzapreti',
                'name'           => 'Strozzapreti (300g)',
                'ingredients_de' => 'Steinpilzsauce mit Speck, Grana Padano, Basilikum',
                'ingredients_en' => 'Porcini mushroom sauce with crispy speck, Grana Padano, basil',
                'base_price'     => 13.30,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'serving_size'   => '300g',
                'allergens'      => ['A', 'C', 'F', 'G'],
            ],
            [
                'category_id'    => $categories['pasta-fatta-in-casa']->id,
                'slug'           => 'gramigna-panna-salsiccia',
                'name'           => 'Gramigna Panna Salsiccia (350g)',
                'ingredients_de' => 'Obersauce mit Salsiccia Wurst, Grana Padano, Basilikum',
                'ingredients_en' => 'Cream sauce with Italian salsiccia sausage, Grana Padano, fresh basil',
                'base_price'     => 13.50,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'serving_size'   => '350g',
                'allergens'      => ['A', 'C', 'G'],
            ],
            [
                'category_id'    => $categories['pasta-fatta-in-casa']->id,
                'slug'           => 'lasagne-caserecce',
                'name'           => 'Lasagne Caserecce (500g)',
                'ingredients_de' => 'Ragú Bolognese (gemischt), Béchamelsauce, Grana Padano',
                'ingredients_en' => 'Traditional layered lasagna with mixed beef/pork ragù, béchamel, Grana Padano',
                'base_price'     => 13.90,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'serving_size'   => '500g',
                'allergens'      => ['A', 'C', 'G', 'L'],
            ],

            // Category 6: Dolci (Items 40 - 43)
            [
                'category_id'    => $categories['dolci']->id,
                'slug'           => 'dolce-vita',
                'name'           => 'Dolce Vita (Für 2 Personen)',
                'ingredients_de' => 'Süße Pizza mit Nutella und frischen Früchten',
                'ingredients_en' => 'Sweet wood-fired dessert pizza with warm Nutella and fresh fruit',
                'base_price'     => 12.90,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'allergens'      => ['A', 'F', 'G', 'H'],
            ],
            [
                'category_id'    => $categories['dolci']->id,
                'slug'           => 'roccia',
                'name'           => 'Roccia (Für 2 Personen)',
                'ingredients_de' => 'Süße Pizza mit Pistaziencreme, Ferrero Rocher und frischen Früchten',
                'ingredients_en' => 'Sweet pizza with Sicilian pistachio cream, Ferrero Rocher pralines, and fresh berries',
                'base_price'     => 13.90,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'allergens'      => ['A', 'F', 'G', 'H'],
            ],
            [
                'category_id'    => $categories['dolci']->id,
                'slug'           => 'hausgemachtes-tiramisu',
                'name'           => 'Hausgemachtes Tiramisu (ohne Alkohol)',
                'ingredients_de' => 'Klassisches neapolitanisches Tiramisù mit Mascarponecreme und Savoiardi (ohne Alkohol)',
                'ingredients_en' => 'Authentic homemade tiramisu with fresh mascarpone and coffee-dipped savoiardi (alcohol-free)',
                'base_price'     => 6.50,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'allergens'      => ['A', 'G'],
            ],
            [
                'category_id'    => $categories['dolci']->id,
                'slug'           => 'pistazienprofiterol',
                'name'           => 'Pistazienprofiterol',
                'ingredients_de' => 'Brandteigbällchen gefüllt mit samtiger Pistaziencreme',
                'ingredients_en' => 'Choux pastry profiteroles filled with velvety Sicilian pistachio cream',
                'base_price'     => 6.50,
                'tax_rate'       => 10.00,
                'is_alcoholic'   => false,
                'allergens'      => ['A', 'C', 'G', 'H'],
            ],

            // Category 7: Getränke & Italienisches Spezial-Bier (Items 44 - 51)
            [
                'category_id'    => $categories['getraenke-bier']->id,
                'slug'           => 'san-benedetto-still',
                'name'           => 'San Benedetto still (0,5L)',
                'ingredients_de' => 'Italienisches natürliches Mineralwasser ohne Kohlensäure',
                'ingredients_en' => 'Italian natural still mineral water',
                'base_price'     => 2.20,
                'tax_rate'       => 10.00, // Non-alcoholic soft beverage: 10% VAT
                'is_alcoholic'   => false,
                'serving_size'   => '0,5L',
                'allergens'      => [],
            ],
            [
                'category_id'    => $categories['getraenke-bier']->id,
                'slug'           => 'san-benedetto-prickelnd',
                'name'           => 'San Benedetto prickelnd (0,5L)',
                'ingredients_de' => 'Italienisches natürliches Mineralwasser mit Kohlensäure',
                'ingredients_en' => 'Italian sparkling mineral water',
                'base_price'     => 2.20,
                'tax_rate'       => 10.00, // Non-alcoholic soft beverage: 10% VAT
                'is_alcoholic'   => false,
                'serving_size'   => '0,5L',
                'allergens'      => [],
            ],
            [
                'category_id'    => $categories['getraenke-bier']->id,
                'slug'           => 'fritz-kola',
                'name'           => 'Fritz-Kola / Fritz-Kola Super Zero (0,33L)',
                'ingredients_de' => 'Kultige Kola mit viel Koffein oder zuckerfreie Super Zero Variante',
                'ingredients_en' => 'Classic Fritz-Kola or zero-sugar Super Zero',
                'base_price'     => 3.70,
                'tax_rate'       => 10.00, // Non-alcoholic: 10% VAT
                'is_alcoholic'   => false,
                'serving_size'   => '0,33L',
                'allergens'      => [],
            ],
            [
                'category_id'    => $categories['getraenke-bier']->id,
                'slug'           => 'fritz-kola-schorle',
                'name'           => 'Fritz-Kola Bio Apfelschorle / Traubenschorle (0,33L)',
                'ingredients_de' => 'Bio-Fruchtsaftschorlen von Fritz',
                'ingredients_en' => 'Organic apple or grape sparkling juice',
                'base_price'     => 3.70,
                'tax_rate'       => 10.00, // Non-alcoholic: 10% VAT
                'is_alcoholic'   => false,
                'serving_size'   => '0,33L',
                'allergens'      => [],
            ],
            [
                'category_id'    => $categories['getraenke-bier']->id,
                'slug'           => 'estathe-pesca-limone',
                'name'           => 'Estathé Pesca / Limone',
                'ingredients_de' => 'Traditioneller italienischer Eistee in den Sorten Pfirsich oder Zitrone',
                'ingredients_en' => 'Authentic Italian iced tea in peach or lemon flavor',
                'base_price'     => 3.50,
                'tax_rate'       => 10.00, // Non-alcoholic: 10% VAT
                'is_alcoholic'   => false,
                'serving_size'   => '0,33L',
                'allergens'      => [],
            ],
            [
                'category_id'    => $categories['getraenke-bier']->id,
                'slug'           => 'ichnusa-non-filtrata',
                'name'           => 'Ichnusa non-filtrata (0,33L)',
                'ingredients_de' => 'Sardisches unfiltriertes Spezialbier mit vollmundigem Geschmack',
                'ingredients_en' => 'Unfiltered Sardinian lager beer with a full-bodied flavor',
                'base_price'     => 4.50,
                'tax_rate'       => 20.00, // Alcoholic beverage: 20% Austrian VAT
                'is_alcoholic'   => true,
                'serving_size'   => '0,33L',
                'allergens'      => ['A'],
            ],
            [
                'category_id'    => $categories['getraenke-bier']->id,
                'slug'           => 'birra-moretti',
                'name'           => 'Birra Moretti (0,33L)',
                'ingredients_de' => 'Italienischer Bierklassiker nach traditioneller Brauart',
                'ingredients_en' => 'Classic Italian golden lager brewed using the original 1859 recipe',
                'base_price'     => 4.50,
                'tax_rate'       => 20.00, // Alcoholic beverage: 20% Austrian VAT
                'is_alcoholic'   => true,
                'serving_size'   => '0,33L',
                'allergens'      => ['A'],
            ],
            [
                'category_id'    => $categories['getraenke-bier']->id,
                'slug'           => 'messina-cristalli-di-sale',
                'name'           => 'Messina Cristalli di Sale (0,33L)',
                'ingredients_de' => 'Sizilianisches Spezialbier gebraut mit sizilianischen Meersalzkristallen',
                'ingredients_en' => 'Specialty Sicilian lager brewed with authentic Sicilian sea salt crystals',
                'base_price'     => 4.50,
                'tax_rate'       => 20.00, // Alcoholic beverage: 20% Austrian VAT
                'is_alcoholic'   => true,
                'serving_size'   => '0,33L',
                'allergens'      => ['A'],
            ],
        ];

        // 3. Populate database with items and sync allergens
        foreach ($items as $itemData) {
            $allergenCodes = $itemData['allergens'] ?? [];
            unset($itemData['allergens']);

            $menuItem = MenuItem::updateOrCreate(
                ['slug' => $itemData['slug']],
                $itemData
            );

            if (!empty($allergenCodes)) {
                $menuItem->allergens()->sync($allergenCodes);
            }
        }
    }
}
